flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/supermario/hilt.git
    commit: 590ca68
extra-deps:
- heroku-0.1.2.3
- heroku-persistent-0.2.0
resolver: lts-8.23
